merge_queue:
  max_parallel_checks: 2
  mode: serial

conflict_resolvers:
  - language: typescript
    directories:
      - /trusted

queue_rules:
  - name: vm4-typescript-dir-scope-261010
    batch_size: 2
    batch_max_wait_time: 5 min
    queue_conditions:
      - title = VM4 TYPESCRIPT DIR SCOPE 261010
    merge_conditions:
      - check-success = vm4-never-typescript-dir-scope-261010
    merge_method: merge-batch
